# Generated by Django 4.1.3 on 2022-11-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
