# Generated by Django 4.1.3 on 2022-11-25 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todoapp", "0002_alter_item_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="todolist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(name="TodoList",),
    ]
