# Generated by Django 4.1.3 on 2022-11-25 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todoapp", "0003_alter_item_todolist_delete_todolist"),
    ]

    operations = [
        migrations.AlterModelOptions(name="item", options={"ordering": ["complete"]},),
        migrations.RemoveField(model_name="item", name="todolist",),
        migrations.AddField(
            model_name="item",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
