# Generated by Django 4.1.2 on 2022-11-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0004_alter_item_options_remove_item_todolist_item_user"),
    ]

    operations = [
        migrations.AlterModelOptions(name="item", options={},),
    ]
